---
- name: Add unattended-upgrades file(s)
  ansible.builtin.template: 
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart unattended-upgrades service
