---
- name: Update repo cache and install a unattended-upgrades package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - unattended-upgrades
