---
- name: Converge
  hosts: all
  tasks:
    - name: Install requirements for Debian
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - gnupg
    - name: Include leadlineit.unattended
      ansible.builtin.include_role:
        name: leadlineit.unattended
